export default config = {
    course: {
      title: "Courses",
      apiGet: "/admin/courses",
      apiDelete: "/admin/courses",
      idKey: "courseCode",
      nameKey: "courseName",
      addText: "+ Add Course",
      formFields: {
        courseName: { value: "", placeholder: "Course Name" },
        courseCode: { value: "", placeholder: "Course Code" },
      },
      tableHeading: ["Course Name", "Course Code"],
      tableColumn: ["courseName", "courseCode"],
      apiEndPointSingle: "courses",
      apiEndPointBulk: "importCourses",
    },
    faculty: {
      title: "Faculty Available",
      apiGet: "/admin/faculty",
      apiDelete: "/admin/faculty",
      idKey: "teacherId",
      nameKey: "fName",
      addText: "+ Add Faculty",
      formFields: {
        fName: { value: "", placeholder: "Name" },
        teacherId: { value: "", placeholder: "Teacher ID" },
        username: { value: "", placeholder: "Username" },
        password: { value: "", placeholder: "Password" },
        schoolName: { value: "", placeholder: "School Name" },
      },
      tableHeading: ["Faculty Name", "Faculty-ID", "School Name"],
      tableColumn: ["fName", "teacherId", "schoolName"],
      apiEndPointSingle: "faculty",
      apiEndPointBulk: "faculty/import",
    },
    room: {
      title: "Rooms Available",
      apiGet: "/admin/examRooms",
      apiDelete: "/admin/faculty",
      idKey: "roomNo",
      nameKey: "buildingName",
      addText: "+ Add Room",
      formFields: {
        buildingName: { value: "", placeholder: "Building Name" },
        roomNo: { value: "", placeholder: "Room No." },
        capacity: { value: "", placeholder: "Capacity" },
      },
      tableHeading: ["Building Name", "Room No", "Capacity"],
      tableColumn: ["buildingName", "roomNo", "capacity"],
      apiEndPointSingle: "faculty",
      apiEndPointBulk: "roomImport",
    },
    ExamDuty: {
      title: "Exam Duty",
      apiGet: `/admin/duty`,
      apiDelete: "/admin/duty",
      idKey: "teacherId",
      nameKey: "fName",
      addText: "+ Assign Duty",
      formFields: {
        teacherId: { value: "", placeholder: "Faculty-ID" },
        buildingName: { value: "", placeholder: "Building Name" },
        roomNo: { value: "", placeholder: "Room no." },
        shift: { value: "", placeholder: "Shift" },
        date: { value: "", placeholder: "Date" },
      },
      tableHeading: [
        "Faculty Name",
        "Faculty-ID",
        "Building Name",
        "Room No.",
        "Shift",
        "Date",
      ],
      tableColumn: [
        "fName",
        "teacherId",
        "buildingName",
        "roomNo",
        "shift",
        "date",
      ],
      apiEndPointSingle: "duty",
      apiEndPointBulk: "duty/import",
    },
  };